services:
  mysql:
    container_name: mysql-tdlm-bsn
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tdlm
      MYSQL_USER: tdlm
      MYSQL_PASSWORD: tdlm
    ports:
      - "3306:3306"
    networks:
      - tdlm-net
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin-tdlm
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8082:80"
    networks:
      - tdlm-net
    depends_on:
      - mysql

  redis:
    container_name: redis-tdlm
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tdlm-net
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-commander:
    container_name: redis-commander-tdlm
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"  # Access Redis Commander UI at http://localhost:8081
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - tdlm-net
    depends_on:
      - redis

networks:
  tdlm-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
